#!/bin/sh

#Fix for sdk on archlinux
sed -i -e 's,/\(usr\|lib\|etc\)/,/###/,g' ./staging_dir/host/lib/libc.so.6
make image PROFILE=tl-mr3020-v1 PACKAGES="block-mount kmod-fs-f2fs kmod-usb-storage mkf2fs f2fsck kmod-usb-ohci kmod-usb-uhci -ip6tables -ppp -ppp-mod-pppoe -kmod-ipt-nathelper -odhcp6c"
